# Generated by Django 6.0.1 on 2026-01-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_task_assignees'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('title',)},
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
